service: faviewer

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

package:
  include:
    - web/dist/**
    - api/dist/**

functions:
  graphql:
    handler: handler.graphql
    events:
      - httpApi:
          method: POST
          path: /graphql/{param}

resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.siteName}
        WebsiteConfiguration:
          IndexDocument: index.html
    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: '*'
              Action:
                - s3:GetObject
              Resource:
                Fn::Join: ['', ['arn:aws:s3:::', { 'Ref': 'StaticSite' }, '/*']]

custom:
  siteName: fa-viewer-web-bucket.com
  s3Sync:
    - bucketName: ${self:custom.siteName}
      localDir: web/dist
