name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Yarn install and build
        run: |
          yarn install --frozen-lockfile
          yarn rw build
          cd ./backend && yarn install --frozen-lockfile && cd ..
        env:
          CI: true
      - name: AWS Deployment
        run: |
          sls config credentials --provider aws --conceal --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          yarn run sls deploy
